name: pr

on:
  push:
    branches:
      - main
      - develop
      - staging
      - muginsk
  pull_request:
    branches:
      - main
      - develop
      - staging
      - muginsk

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Install Google Chrome (fixa versão estável)
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          google-chrome --version

      - name: Install ChromeDriver versão fixa (114)
        run: |
          CHROMEDRIVER_VERSION=114.0.5735.90
          echo "Usando versão fixa do ChromeDriver: $CHROMEDRIVER_VERSION"

          wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O chromedriver.zip
          unzip chromedriver.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Instalar dependências do Chrome headless
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libappindicator3-1 fonts-liberation
          sudo apt-get install -y libxss1 libgdk-pixbuf2.0-0 libnss3 libatk-bridge2.0-0 libatk1.0-0 libcups2 libx11-xcb1 xvfb

      - name: Run Tests with Maven (Headless)
        run: |
          sudo Xvfb :99 -ac &
          export DISPLAY=:99
          mvn clean test
