name: pr

on:
  push:
    branches:
      - main
      - develop
      - staging
      - Muginsk
  pull_request:
    branches:
      - main
      - develop
      - staging
      - Muginsk

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Install Google Chrome and ChromeDriver
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y # Garante que todos os pacotes estão atualizados
          sudo apt-get install -y google-chrome-stable
          # Get Chrome version
          CHROME_VERSION=$(google-chrome --version | grep -oP '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
          # Get the corresponding chromedriver version
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          # Download and install ChromeDriver
          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" -O chromedriver.zip
          unzip chromedriver.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version
          google-chrome --version

      - name: Install dependencies for headless Chrome
        run: |
          sudo apt-get install -y libappindicator3-1 fonts-liberation
          sudo apt-get install -y libxss1 libgdk-pixbuf2.0-0 libnss3 libatk-bridge2.0-0 libatk1.0-0 libcups2 libx11-xcb1

      - name: Set up Google Chrome as headless
        run: |
          echo "Running Chrome in headless mode"
          export DISPLAY=:99.0
          sudo apt-get install -y xvfb
          sudo Xvfb :99 -ac &

      - name: Run Tests with Maven
        run: mvn clean test
