name: pr

on:
  push:
    branches:
      - main
      - develop
      - staging
      - Muginsk
  pull_request:
    branches:
      - main
      - develop
      - staging
      - Muginsk

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Install Google Chrome
        run: |
          sudo apt-get update -y
          sudo apt-get install -y google-chrome-stable
          google-chrome --version

      - name: Install ChromeDriver compatível
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+' | head -1)
          echo "Chrome major version: $CHROME_VERSION"

          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION" || echo "114.0.5735.90") # fallback
          echo "Matching ChromeDriver version: $CHROMEDRIVER_VERSION"

          wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O chromedriver.zip
          unzip chromedriver.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Instalar libs para Chrome headless
        run: |
          sudo apt-get install -y libappindicator3-1 fonts-liberation \
            libxss1 libgdk-pixbuf2.0-0 libnss3 libatk-bridge2.0-0 \
            libatk1.0-0 libcups2 libx11-xcb1 xvfb

      - name: Run Tests com Maven + headless
        env:
          CI: true  # Isso ativa o headless no seu código Java!
        run: |
          sudo Xvfb :99 -ac & # roda o X virtual
          export DISPLAY=:99
          mvn clean test
